before:
  hooks:
    - go install github.com/mitchellh/golicense
    - go run cmd/swagger/main.go containerssh-authconfig-openapi.json
    - go test
builds:
  - id: containerssh-linux
    main: cmd/containerssh/main.go
    binary: "containerssh"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - cmd: go run cmd/license-report/main.go golicense.json build/containerssh-linux_linux_amd64/containerssh NOTICE.md
          dir: "{{ dir .Path }}/../../"
  - id: containerssh-windows
    main: cmd/containerssh/main.go
    binary: "containerssh"
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: containerssh-darwin
    main: cmd/containerssh/main.go
    binary: "containerssh"
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: containerssh-auditlog-decoder
    main: cmd/containerssh-auditlog-decoder/main.go
    binary: "containerssh-auditlog-decoder"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: containerssh-testauthconfigserver
    main: cmd/containerssh-testauthconfigserver/main.go
    binary: "containerssh-testauthconfigserver"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - builds:
      - containerssh-linux
      - containerssh-windows
      - containerssh-darwin
      - containerssh-testauthconfigserver
      - containerssh-auditlog-decoder
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - NOTICE.md
      - config.example.yaml
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - containerssh
    image_templates:
      - "containerssh/containerssh:latest"
      - "containerssh/containerssh:{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh:latest"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh:{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile.goreleaser
    builds:
      - containerssh-linux
    extra_files:
      - LICENSE.md
      - NOTICE.md
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=ContainerSSH"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation=https://containerssh.github.io"
    skip_push: auto
  - goos: linux
    goarch: amd64
    binaries:
      - containerssh-testauthconfigserver
    image_templates:
      - "containerssh/containerssh-test-authconfig:latest"
      - "containerssh/containerssh-test-authconfig:{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh-test-authconfig:latest"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh-test-authconfig:{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile-testauthconfigserver.goreleaser
    builds:
      - containerssh-testauthconfigserver
    extra_files:
      - LICENSE.md
      - NOTICE.md
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=ContainerSSH Auth-Config Server"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation=https://containerssh.github.io"
    skip_push: auto
  - goos: linux
    goarch: amd64
    binaries:
      - containerssh
    image_templates:
      - "containerssh/containerssh:{{ .Tag }}"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    builds:
      - containerssh-linux
    extra_files:
      - LICENSE.md
      - NOTICE.md
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=ContainerSSH"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation=https://containerssh.github.io"
    skip_push: false
  - goos: linux
    goarch: amd64
    binaries:
      - containerssh-testauthconfigserver
    image_templates:
      - "containerssh/containerssh-test-authconfig:{{ .Tag }}"
      - "docker.pkg.github.com/containerssh/containerssh/containerssh-test-authconfig:{{ .Tag }}"
    dockerfile: Dockerfile-testauthconfigserver.goreleaser
    builds:
      - containerssh-testauthconfigserver
    extra_files:
      - LICENSE.md
      - NOTICE.md
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=ContainerSSH Auth-Config Server"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation=https://containerssh.github.io"
    skip_push: false
nfpms:
  - vendor: Janos Pasztor
    homepage: https://pasztor.at
    maintainer: Janos Pasztor <janos@pasztor.at>
    description: An SSH server that launches Docker containers and Kubernetes pods
    license: MIT
    builds:
      - containerssh-linux
      - containerssh-testauthconfigserver
      - containerssh-auditlog-decoder
    formats:
      - deb
      - rpm
    empty_folders:
      - /etc/containerssh
    bindir: /usr/sbin
    suggests:
      - docker
    files:
      LICENSE.md: /usr/share/doc/containerssh/LICENSE.md
    config_files:
      config.example.yaml: /etc/containerssh/config.yaml
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
dist: build
release:
  github:
    owner: containerssh
    name: containerssh
  prerelease: auto
  extra_files:
    - glob: LICENSE.md
    - glob: NOTICE.md
    - glob: containerssh-authconfig-openapi.json
