name: Lint
on:
  push:
  pull_request:
jobs:
  test:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2
          args: --timeout=5m -E asciicheck -E bodyclose -E dupl -E errorlint -E exportloopref -E funlen
