name: Build
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Update libcontainerssh
        run: |
          go get go.containerssh.io/libcontainerssh@main
          go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist
      - uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: build
          if-no-files-found: error